# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value


labels:
  api:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  worker:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  housekeeping:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  test:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  health_manager:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled
  anchor:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

release_group: null

images:
  pull_policy: IfNotPresent
  tags:
    dep_check: 'quay.io/stackanetes/kubernetes-entrypoint:v0.3.0'
    db_drop: docker.io/openstackhelm/heat:newton
    db_init: docker.io/openstackhelm/heat:newton
    ks_user: docker.io/openstackhelm/heat:newton
    ks_service: docker.io/openstackhelm/heat:newton
    ks_endpoints: docker.io/openstackhelm/heat:newton
    octavia_db_sync: docker.io/kolla/ubuntu-source-octavia-api:4.0.0
    octavia_api: docker.io/kolla/ubuntu-source-octavia-api:4.0.0
    octavia_worker: docker.io/kolla/ubuntu-source-octavia-worker:4.0.0
    octavia_housekeeping: docker.io/kolla/ubuntu-source-octavia-housekeeping:4.0.0
    octavia_health_manager:  docker.io/kolla/ubuntu-source-octavia-health-manager:4.0.0
    octavia_anchor: docker.io/openstacksecurity/anchor:latest
    image_repo_sync: docker.io/docker:17.07.0
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

bootstrap:
  enabled: false
  ks_user: octavia
  script: |
    openstack token issue

pod:
  user:
    octavia:
      uid: 42437
  affinity:
      anti:
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        topologyKey:
          default: kubernetes.io/hostname
  mounts:
    octavia_api:
      init_container: null
      octavia_api:
    octavia_worker:
      init_container: null
      octavia_worker:
    octavia_housekeeping:
      init_container: null
      octavia_housekeeping:
    octavia_health_manager:
      init_container: null
      octavia_health_manager:
    octavia_tests:
      init_container: null
      octavia_tests:
    octavia_anchor:
      init_container: null
      octavia_anchor:  
  replicas:
    api: 1
    worker: 1
    housekeeping: 1
    health_manager: 1
    anchor: 1
  lifecycle:
    upgrades:
      deployments:
        revision_history: 3
        pod_replacement_strategy: RollingUpdate
        rolling_update:
          max_unavailable: 1
          max_surge: 3
    disruption_budget:
      api:
        min_available: 0
    termination_grace_period:
      api:
        timeout: 30
  resources:
    enabled: false
    api:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    worker:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    health_monitor:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    housekeeping:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    anchor:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    jobs:
      db_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      db_init:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      db_drop:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_user:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_service:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      ks_endpoints:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      rabbit_init:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      bootstrap:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      tests:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

volume:
  enabled: true
  class_name: general
  size: 1Gi

conf:
  octavia:
    DEFAULT:
      debug: False
    api_settings:
      #NOTE(portdirect): the bind port should not be defined, and is manipulated
      # via the endpoints section.
      bind_port: null
      bind_host: 0.0.0.0
      api_v1_enabled: False
      auth_strategy: keystone
    keystone_authtoken:
      auth_type: password
      auth_version: v3
      memcache_security_strategy: ENCRYPT
    service_auth:
      auth_type: password
      auth_version: v3
      memcache_security_strategy: ENCRYPT
    database:
      max_retries: -1
    oslo_messaging:
      topic: octavia_prov
    health_manager:
      bind_ip: 0.0.0.0
      bind_port: null
      controller_ip_port_list: null
      heartbeat_key: null
    controller_worker:
      amp_image_tag: amphora
      amp_flavor_id: null
      amp_boot_network_list: null
      amp_secgroup_list: null
      amp_ssh_key_name: null
      compute_driver: compute_nova_driver
      amphora_driver: amphora_haproxy_rest_driver
      network_driver: allowed_address_pairs_driver
      distributor_driver: single_VIP_amphora
      client_ca: /etc/anchor/server-ca/ca.crt
    certificates:
      cert_generator: anchor_cert_generator
      ca_certificate: /etc/anchor/server-ca/ca.crt
      ca_private_key: /etc/anchor/server-ca/ca.key
      signing_digest: sha256
      storage_path: /key/certs
      cert_valid_days: 18250
    haproxy_amphora:
      server_ca: /etc/anchor/server-ca/ca.crt
      client_cert: null
    anchor:
      username: octavia
  anchor:
    authentication:
      static:
        backend: static
    signing_ca:
      server:
        backend: anchor
        cert_path: /etc/anchor/server-ca/ca.crt
        key_path: /etc/anchor/server-ca/ca.key
        cert_valid_days: 18250
        output_path: /key/certs
        signing_hash: sha256
        valid_hours: 24
      client:
        backend: anchor
        cert_path: /etc/anchor/server-ca/ca.crt
        key_path: /etc/anchor/server-ca/ca.key
        cert_valid_days: 18250
        output_path: /key/certs
        signing_hash: sha256
        valid_hours: 24
    registration_authority:
      server:
        authentication: static
        signing_ca: server
        validators:
          source_cidrs:
            cidrs:
              - 0.0.0.0/0
      client:
        authentication: static
        signing_ca: client
        validators:
          source_cidrs:
            cidrs:
              - 0.0.0.0/0
    audit:
      target: log
  rally_tests:
    tests:
  policy:
    context_is_admin: "role:admin or role:load-balancer_admin"
    admin_or_owner: "is_admin:True or project_id:%(project_id)s"
    load-balancer:read: "rule:admin_or_owner"
    load-balancer:read-global: "is_admin:True"
    load-balancer:write: "rule:admin_or_owner"
    load-balancer:read-quota: "rule:admin_or_owner"
    load-balancer:read-quota-global: "is_admin:True"
    load-balancer:write-quota: "is_admin:True"
  glance:
    DEFAULT:
      #NOTE(portdirect): the bind port should not be defined, and is manipulated

network:
  api:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx-cluster"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: false
      port: 30004
  health_manager:
    ingress:
      public: false
      classes:
        namespace: "nginx"
        cluster: "nginx-cluster"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: true
      port: 30005
  pki_api:
    ingress:
      public: false
      classes:
        namespace: "nginx"
        cluster: "nginx-cluster"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: false

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - octavia-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    api:
      jobs:
        - octavia-db-sync
        - octavia-ks-user
        - octavia-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: identity
        - endpoint: internal
          service: oslo_messaging
    worker:
      jobs:
        - octavia-db-sync
        - octavia-ks-user
        - octavia-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: identity
        - endpoint: internal
          service: oslo_messaging
    housekeeping:
      jobs:
        - octavia-db-sync
        - octavia-ks-user
        - octavia-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: identity
        - endpoint: internal
          service: oslo_messaging
    health_manager:
      jobs:
        - octavia-db-sync
        - octavia-ks-user
        - octavia-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: identity
        - endpoint: internal
          service: oslo_messaging
    anchor:
      jobs:
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: identity
    housekeeping:
      jobs:
        - octavia-db-sync
        - octavia-ks-user
        - octavia-ks-endpoints
    db_drop:
      services:
        - endpoint: internal
          service: oslo_db
    db_init:
      services:
        - endpoint: internal
          service: oslo_db
    db_sync:
      jobs:
        - octavia-db-init
      services:
        - endpoint: internal
          service: oslo_db
    ks_endpoints:
      jobs:
        - octavia-ks-service
      services:
        - endpoint: internal
          service: identity
    ks_service:
      services:
        - endpoint: internal
          service: identity
    ks_user:
      services:
        - endpoint: internal
          service: identity
    rabbit_init:
      services:
      - service: oslo_messaging
        endpoint: internal
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry

# Names of secrets used by bootstrap and environmental checks
secrets:
  identity:
    admin: octavia-keystone-admin
    octavia: octavia-keystone-user
    test: octavia-keystone-test
  oslo_db:
    admin: octavia-db-admin
    octavia: octavia-db-user
  oslo_messaging:
    admin: octavia-rabbitmq-admin
    octavia: octavia-rabbitmq-user

# typically overridden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  oslo_db:
    auth:
      admin:
        username: root
        password: password
      octavia:
        username: octavia
        password: password
    hosts:
      default: mariadb
    host_fqdn_override:
      default: null
    path: /octavia
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
  oslo_messaging:
    auth:
      admin:
        username: rabbitmq
        password: password
      octavia:
        username: octavia
        password: password
    hosts:
      default: rabbitmq
    host_fqdn_override:
      default: null
    path: /
    scheme: rabbit
    port:
      amqp:
        default: 5672
      http:
        default: 15672
  oslo_cache:
    auth:
      # NOTE(portdirect): this is used to define the value for keystone
      # authtoken cache encryption key, if not set it will be populated
      # automatically with a random value, but to take advantage of
      # this feature all services should be set to use the same key,
      # and memcache service.
      memcache_secret_key: null
    hosts:
      default: memcached
    host_fqdn_override:
      default: null
    port:
      memcache:
        default: 11211
  identity:
    name: keystone
    auth:
      admin:
        region_name: RegionOne
        username: admin
        password: password
        project_name: admin
        user_domain_name: default
        project_domain_name: default
      octavia:
        role: admin
        region_name: RegionOne
        username: octavia
        password: password
        project_name: service
        user_domain_name: default
        project_domain_name: default
      test:
        role: admin
        region_name: RegionOne
        username: test
        password: password
        project_name: test
        user_domain_name: default
        project_domain_name: default
    hosts:
      default: keystone-api
      public: keystone
    host_fqdn_override:
      default: null
    path:
      default: /v3
    scheme:
      default: http
    port:
      admin:
        default: 35357
      api:
        default: 80
  load_balancer:
    name: octavia
    hosts:
      default: octavia-api
      public: octavia
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: 'http'
    port:
      api:
        default: 9876
        public: 80
  health_manager:
    name: health_manager
    hosts:
      default: octavia-health-manager
      public: octavia-health
    host_fqdn_override:
      default: null
    path:
      default: null
    scheme:
      default: null
    port:
      health_manager:
        default: 5555
  pki:
    name: anchor
    hosts:
      default: anchor-api
    host_fqdn_override:
      default: null
    path:
      default: /v1/sign/server
    scheme:
      default: 'http'
    port:
      api:
        default: 5016

manifests:
  configmap_bin: true
  configmap_etc: true
  deployment_api: true
  ingress_api: true
  job_anchor_bootstrap: true
  job_bootstrap: false
  job_db_init: true
  job_db_sync: true
  job_db_drop: false
  job_ks_endpoints: true
  job_ks_service: true
  job_ks_user: true
  job_rabbit_init: true
  job_image_repo_sync: true
  pdb_api: true
  pod_rally_test: true
  secret_db: true
  secret_keystone: true
  secret_rabbitmq: true
  service_ingress_api: true
  service_api: true
  service_health_manager: true
  service_anchor: true
  statefulset_worker: true
  statefulset_housekeeping: true
  statefulset_health_manager: true
  statefulset_anchor: true
