# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  tags:
    mariadb: docker.io/mariadb:10.2.12
    dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.2.1
  pull_policy: IfNotPresent

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

pod:
  affinity:
    anti:
      type:
        default: preferredDuringSchedulingIgnoredDuringExecution
      topologyKey:
        default: kubernetes.io/hostname
  replicas:
    server: 3
  lifecycle:
    disruption_budget:
      mariadb:
        min_available: 0
  resources:
    enabled: false
    server:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"

dependencies:
  mariadb:
    jobs: null
    services: null

force_bootstrap: false

volume:
  enabled: true
  class_name: general
  size: 5Gi

database:
  config_override: null
  # Any configuration here will override the base config.
  # config_override: |-
  #   [mysqld]
  #   wsrep_slave_threads=1

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  cluster_domain_suffix: cluster.local
  oslo_db:
    auth:
      admin:
        username: root
        password: password
    hosts:
      default: mariadb
      discovery: mariadb-discovery
    host_fqdn_override:
      default: null
    path: null
    scheme: mysql+pymysql
    port:
      mysql:
        default: 3306
      wsrep:
        default: 4567

manifests:
  configmap_bin: true
  configmap_etc: true
  pdb_server: true
  secret_db: true
  secret_etc: true
  service_discovery: true
  service: true
  statefulset: true
