{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if and .Values.manifests.job_anchor_bootstrap }}
{{- $envAll := . }}
{{- range $key1, $anchorBootstrapKey := tuple "server" "client" }}
{{- $jobName := print $anchorBootstrapKey "-anchor-bootstrap " }}

{{- $dependencies := $envAll.Values.dependencies.static.job_anchor_bootstrap }}

{{- $serviceAccountName := print "anchor-" $jobName }}
{{ tuple $envAll $dependencies $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ $serviceAccountName }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $envAll.Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: anchor-{{ $jobName }}
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "anchor" $jobName | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      restartPolicy: OnFailure
      nodeSelector:
        {{ $envAll.Values.labels.job.node_selector_key }}: {{ $envAll.Values.labels.job.node_selector_value }}
      initContainers:
{{ tuple $envAll $dependencies list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name:  anchor-{{ $jobName }}
          image: {{ $envAll.Values.images.tags.ceph_config_helper }}
          imagePullPolicy: {{ $envAll.Values.images.pull_policy }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.secret_provisioning | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: DEPLOYMENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_SECRET_NAME
              value: octavia-{{ $anchorBootstrapKey }}-ca-cert 
            - name: CA
              value: {{ $anchorBootstrapKey }}
          securityContext:
            runAsUser: 0
{{ tuple $envAll $envAll.Values.pod.resources.anchor | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          command:
            - /tmp/anchor-init.sh
          volumeMounts:
            - name: octavia-bin
              mountPath: /tmp/anchor-init.sh
              subPath: anchor-init.sh
              readOnly: true
      volumes:
        - name: octavia-bin
          configMap:
            name: octavia-bin
            defaultMode: 0555
{{- end }}
{{- end }}
